api/urls.py
from django.urls import path 
from .views import bbs #список новостей
from .views import BbDetailView#вывод отдельных сведений о выбранной новости
from .views import comments #вывод и добавление комментариев



urlpatterns = [
    path('bbs/<int:pk>/comments/', comments),
    path('bbs/<int:pk>/', BbDetailView.as_view()),
    path('bbs/', bbs),
]

astron/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('api/', include('api.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path 
from .views import index#главная
from .views import other_page#другие страницы
from .views import AstroLoginView#вход
from .views import profile#профиль
from .views import AstroLogoutView#выход
from .views import ChangeUserInfoView#изменение данных
from .views import AstroPasswordChangeView#смена пароля
from .views import RegisterUserView#регистрация
from .views import RegisterDoneView#сообщение о регистрации
from .views import user_activate#активация
from .views import DeleteUserView#удаление профиля 
#from .views import ResetPasswordView#сброс пароля
#from .views import ResetPasswordConfirmView#дтверждение сброса
#from .views import ResetPasswordCompleteView
#from .views import ResetPasswordDoneView
from .views import detail#детали новости
from .views import by_rubric#контроллер для рубрик
from django.conf.urls.static import static 
from astron import settings
from .views import profile_bb_detail#нконтроллер данных о новостях, загруженных пользователем
from .views import profile_bb_add#контроллер добавления новости
from .views import profile_bb_change#контроллер изменения новости
from .views import profile_bb_delete#контроллер удаления новости



app_name = 'main'

urlpatterns = [
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/logout/', AstroLogoutView.as_view(), name='logout'),
    path('accounts/password/change/', AstroPasswordChangeView.as_view(), name='password_change'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/change/<int:pk>/', profile_bb_change, name='profile_bb_change'),
    path('accounts/profile/delete/<int:pk>/', profile_bb_delete, name='profile_bb_delete'),
    path('accounts/profile/add/', profile_bb_add, name='profile_bb_add'),
    path('accounts/profile/<int:pk>/', profile_bb_detail, name='profile_bb_detail'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/login/', AstroLoginView.as_view(), name='login'),
   #path('accounts/password/reset/', ResetPasswordView.as_view(), name='reset'),
   #path('accounts/password/reset/confirm/', ResetPasswordConfirmView.as_view(), name='reset_confirm'),
   #path('accounts/password/reset/done/', ResetPasswordDoneView.as_view(), name='eset_done'),
   #path('accounts/password/reset/complete', ResetPasswordCompleteView.as_view(), name='reset_complete'),
    path('<int:rubric_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_rubric, name='by_rubric'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
]

main/forms.py
from django import forms 
from .models import AstroUser 
from django.contrib.auth import password_validation 
from django.core.exceptions import ValidationError
from .apps import user_registered
from .models import SuperRubric 
from .models import SubRubric 
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from .models import Bb 
from .models import AdditionalImage 
from captcha.fields import CaptchaField 
from .models import Comment 
#класс для ввода данных пользователя 
class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    class Meta:
        model = AstroUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')


#форма для занесения сведений о новом пользователe
class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password_one = forms.CharField(label='Пароль', 
        widget = forms.PasswordInput, 
        help_text = password_validation.password_validators_help_text_html())
    password_two = forms.CharField(label='Пароль(повторно)',
        widget = forms.PasswordInput,
        help_text = 'Введите тот же пароль еще раз для проверки')

    def clean_password_one(self):
        password_one = self.cleaned_data['password_one']
        if password_one:
            password_validation.validate_password(password_one)
        return password_one 

    def clean(self):
        super().clean()
        password_one = self.cleaned_data['password_one']
        password_two = self.cleaned_data['password_two']
        if password_one and password_two and password_one != password_two:
            errors = {'password_two': ValidationError(
                'Введенные вами пароли не совпадают', code = 'password_micmatch')
            }
            raise ValidationError(errors)
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password_one'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registered.send(RegisterUserForm, instance=user)
        return user 
    class Meta:
        model = AstroUser
        fields = ('username', 'email', 'password_one', 'password_two', 'first_name', 'last_name',
                'send_messages')


#создаем поле надрубрики
#@login_required
class SubRubricForm(forms.ModelForm):
    super_rubric = forms.ModelChoiceField(queryset=SuperRubric.objects.all(), 
                                            empty_label=None,
                                            label='Надрубрика',
                                            required=True)
    
    class Meta:
        model = SubRubric
        fields = '__all__'


#форма поиска на сайте
#@login_required
class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=20, label='')

#форма ввода новости
#форма ввода дополнительных иллюстраций
class BbForm(forms.ModelForm):
    class Meta:
        model = Bb 
        fields = '__all__' 
        widgets = {'author': forms.HiddenInput}

AIFormSet = inlineformset_factory(Bb, AdditionalImage, fields='__all__')


#форма комментариев для зарегистрированного пользователя
class UserCommentForm(forms.ModelForm):
    class Meta:
        model = Comment 
        exclude = ('is_active',)
        widgets = {'bb': forms.HiddenInput}

#форма для комментариев для гостей сайта
class GuestCommentForm(forms.ModelForm):
    captcha = CaptchaField(label='Введите текст с картинки', error_messages={'invalid': 'Неправильный текст'})
    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'bb': forms.HiddenInput}

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required 
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin#примесь для зарегистрированных пользователей
from django.views.generic.edit import UpdateView 
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy, reverse
from django.shortcuts import get_object_or_404
from .models import AstroUser
from .forms import ChangeUserInfoForm
from django.contrib.auth.views import PasswordChangeView 
from django.views.generic.edit import CreateView 
from .forms import RegisterUserForm
from django.views.generic.base import TemplateView  
from django.core.signing import BadSignature 
from .utilities import signer 
from django.views.generic.edit import DeleteView 
from django.contrib.auth import logout 
from django.contrib import messages 
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView
from django.core.paginator import Paginator 
from django.db.models import Q 
from .models import SubRubric, Bb
from .forms import SearchForm 
from django.shortcuts import redirect 
from .forms import BbForm
from .forms import AIFormSet
from .models import Comment 
from .forms import UserCommentForm 
from .forms import GuestCommentForm


#реализация контроллера главной страницы с помощью функции
def index(request):
    bbs = Bb.objects.filter(is_active=True)[:10]
    context = {'bbs': bbs}
    return render(request, 'main/index.html', context)

#генератор адресов
def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
        #поднятие исключения
    except TemplateDoesNotExist:
        #перехват исключения и вывод http404
        raise Http404
    return HttpResponse(template.render(request=request))

#контроллер страницы входа - расширение класа loginView
class AstroLoginView(LoginView):
    template_name = 'main/login.html'

#контролер профиля пользователя
@login_required#декоратор функции, подтверждающий, что пользователь вошел
def profile(request):
    bbs = Bb.objects.filter(author=request.user.pk)
    context = {'bbs': bbs}
    return render(request, 'main/profile.html', context)


#раелизация контроллера выхода через класс LogoutView
class AstroLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


#используем класс UpdateView для изменения пользовательских данных
class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AstroUser
    template_name = 'main/ch_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Данные пользователя успешно изменены'
    
    #получаем ключ текущего пользователя
    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk 
        return super().setup(request, *args, **kwargs)
    
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


#онтроллер изменения пароля создаем, расширяя класс PasswordChangeView
class AstroPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_ch.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль успешно изменен'

#контроллеро регистрации пользователя
class RegisterUserView(CreateView):
    model = AstroUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


#вывод сообщения о регистрации пользователя
class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


#контроллер активации
def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/bad.html')
    user = get_object_or_404(AstroUser, username=username)
    if user.is_activated:
        template = 'main/user_is_activated.html'
    else:
        template = 'main/activation_done.html'
        user.is_active = True 
        user.is_activated = True 
        user.save()
    return render(request, template)

#удаление профиля
class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AstroUser
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def post (self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Пользователь удален')
        return super().post(request, *args, **kwargs)
    
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


#
def by_rubric(request, pk):
    rubric = get_object_or_404(SubRubric, pk=pk)
    bbs = Bb.objects.filter(is_active=True, rubric=pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        bbs = bbs.filter(q)
    else:
        keyword = ''

    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(bbs, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1 
    page = paginator.get_page(page_num)
    context = {'rubric': rubric, 'page': page, 'bbs': page.object_list, 'form': form} 
    return render(request, 'main/by_rubric.html', context) 


#функция детального рассмотрения новости и комментариев
def detail(request, rubric_pk, pk):
    #bb = get_object_or_404(Bb, pk=pk)
    bb = Bb.objects.get(pk=pk)
    ais = bb.additionalimage_set.all()
    comments = Comment.objects.filter(bb=pk, is_active=True)
    initial = {'bb': bb.pk}
    if request.user.is_authenticated:
        initial['author'] = request.user.username
        form_class = UserCommentForm
    else:
        form_class = GuestCommentForm
    form = form_class(initial=initial)
    if request.method == 'POST':
        c_form = form_class(request.POST)
        if c_form.is_valid():
            c_form.save()
            messages.add_message(request, messages.SUCCESS, 'Комментарий успешно добавлен')
        else:
            form = c_form
            messages.add_message(request, messages.WARNING, 'Комментарий не добавлен')
    context = {'bb': bb, 'ais': ais, 'comments': comments, 'form': form}
    return render(request, 'main/detail.html', context)
    #context = {'bb': bb, 'ais': ais}
    #return render(request, 'main/profile_detail.html', context)

#контроллер для просмотра сведений о новостях добавленных одним пользователем
@login_required
def profile_bb_detail(request, rubric_pk, pk):
    bb = get_object_or_404(Bb, pk=pk)
    ais = bb.additionalimage_set.all()
    context = {'bb': bb, 'ais': ais}
    return render(request, 'main/detail.html', context)


#контроллер добавления новостей 
@login_required
def profile_bb_add(request):
    if request.method == 'POST':
        form = BbForm(request.POST, request.FILES)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Новость успешно добавлена') 
                return redirect('main:profile')
    else:
        form = BbForm(initial={'author': request.user.pk})
        formset = AIFormSet()
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_bb_add.html', context)
'''
при создании формы перед выводом страницы 
охранения мы заносим в поле author формы ключ текущего
пользователя, который станет автором объявления.
во время сохранения введенного объявления, при создании объектов
формы и набора форм, мы должны передать конструкторам их классов вторым по­
зиционным параметром словарь со всеми полученными файлами (он хранится
в атрибуте FILES объекта запроса). Если мы не сделаем этого, то отправленные
пользователем иллюстрации окажутся потерянными
при сохранении мы сначала выполняем валидацию и сохранение формы
самого объявления. Метод s ave ( ) в качестве результата возвращает сохраненную
запись, и эту запись мы должны передать через параметр instance конструктору
класса набора форм. Это нужно для того, чтобы все дополнительные иллюстрации
после сохранения оказались связанными с объявлением.
'''
#контроллер удаления и редактирования новости
@login_required
def profile_bb_change(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    if request.method == 'POST':
        form = BbForm(request.POST, request.FILES, instance=bb)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Новость отредактирована')
                return redirect('main:profile')
    else:
        form = BbForm(instance=bb)
        formset = AIFormSet(instance=bb)
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_bb_change.html', context)

@login_required
def profile_bb_delete(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    if request.method == 'POST':
        bb.delete()
        messages.add_message(request, messages.SUCCESS, 'Новость удалена')

main/templates/main/by_rubric.html
{% extends 'base/base.html' %} 
{% load thumbnail %} 
{% load static %}
{% load bootstrap4 %}

{% block title %}
    {{ rubric }}
{% endblock title %}

{% block content %}
    <h3 class="mb-2">{{ rubric }}</h3>
    <div class="container-fluid mb-2">
        <div class="row">
            <div class="col">&nbsp;</div>
            <form action="" class="col-md-auto form-inline">
                {% bootstrap_form form show_label=False %} 
                {% bootstrap_button content='Искать' button_type='submit' %} 
            </form>
        </div>
    </div>
    {% if bbs %} 
        <ul class="list-unstyled">
            {% for bb in bbs %} 
            <li class="dropdown-item">
                {% url 'main:detail' rubric_pk=rubric.pk pk=bb.pk as url %} 
                <!--<a href="{{ url }} {{ all }}">
                    {% if bb.image %} 
                        <img src="{% thumbnail bb.image 'default' %}" alt="b" class="mr-3">
                            
                    {% else %} 
                        <img src="{% static 'main/empty.jpg' %}" alt="a" class="mr-3">
                    {% endif %} 
                </a>-->
                <div class="media-body">
                    <h3><a href="{{ url }} {{ all }}">
                        {{ bb.title }}
                    </a></h3>
                    <div>{{ bb.content }}</div>
                    <p class="text-right forn-weight-bold">Источник {{ bb.source }}</p>
                    <p class="text-right font-italic">{{ bb.created_at }}</p>
                </div>
        
            </li>
            {% endfor %}
        </ul> 
    {% endif %} 
{% endblock content %}
    
    

main/templates/main/delete_user.html
{% extends 'base/base.html' %}
{% load bootstrap4 %} 
{% load static %}

{% block title %}
    Удаление профиля
{% endblock title %}

{% block content %}
    <h2>Удаление профиля {{ object.username }}</h2>
    <form action="" method="POST">
        {% csrf_token %} 
        {% buttons submit='Удалить' %} {% endbuttons %} 
    </form>
{% endblock content %}
    

main/templates/main/detail.html
{% extends 'base/base.html' %} 
{% load bootstrap4 %} 
{% load static %}
{% load thumbnail %} 

{% block title %}
    {{ bb.title }} - {{ bb.rubric.name }}
{% endblock title %}

{% block content %}
    <div class="container-fluid mt-3">
        <!--<div class="row">-->
            <div class="col">
                <h3>{{ bb.title }}</h3>
                <p>{{ bb.content }}</p>
                <p class="font-weight-bold">Источник {{ bb.source }}</p>
                <!--<p>{{ bb.contacts }}</p>-->
                <p class="text-right forn-italic">Новость добавлена {{ bb.created_at }}</p>
            </div>
            {% if bb.image %} 
            <div class="col">
                <img src="{{ bb.image.url }}" alt="a" class="rounded float-right">
            {% endif %} 
            <!--<div class="col">
                <h3>{{ bb.title }}</h3>
                <p>{{ bb.content }}</p>
                <p class="font-weight-bold">{{ bb.source }}</p>
                <p>{{ bb.contacts }}</p>
                <p class="text-right forn-italic">Новость добавлена {{ bb.created_at }}</p>
            </div>-->
        </div>
    </div>
    {% if ais %} 
    <div class="d-flex justify-content-between flex-wrap mt-5">
        {% for ai in ais %} 
        <div>
            <img src="{{ ai.image.url }}" alt="b" class="additional-image">
        </div>
        {% endfor %} 
    </div>
    {% endif %} 
    <p>
        <a href="{% url 'main:by_rubric' pk=bb.rubric.pk %} {{ all }}">Назад</a>
    </p>
{% endblock content %}
    
    

main/templates/main/index.html
{% extends 'base/base.html' %} 
{% load thumbnail %} 
{% load static %}
{% load bootstrap4 %}

{% block title %}
    {{ Главная }}
{% endblock title %}

{% block content %}
    <h3 class="mb-2">Последние записи</h3>
    <div class="container-fluid mb-2">
        <form action="" class="col-md-auto form-inline">
            <input type="text">
            <button type="submit">Искать</button> 
        </form>
    {% if bbs %} 
        <ul class="list-unstyled">
            {% for bb in bbs %} 
            <li class="media my-5 p-3 border">
                <div class="media-body">
                    <h3><a href="{% url 'main:detail' rubric_pk=rubric.pk pk=bb.pk as url %}">
                        {{ bb.title }}
                    </a></h3>
                    <div>{{ bb.content }}</div>
                    <p class="text-right forn-weight-bold">Источник {{ bb.source }}</p>
                    <p class="text-right font-italic">{{ bb.created_at }}</p>
                </div>
            </li>
            {% endfor %}
        </ul>
    {% endif %}  
{% endblock content %}
    
    

main/templates/main/logout.html
{% extends 'base/base.html' %} 
{% load bootstrap4 %} 

{% block title %}
    Выход
{% endblock title %}

{% block content %}
   <h3>Выход</h3>
   <p>Вы успешно вышли</p>
{% endblock content %}
    
    

main/templates/main/password_reset_confirm.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}

{% block title %}
    Сброс пароля
{% endblock title %}

{% block content %}
    {% if validlink %}
        <p>Пожалуйста, введите свой новый пароль</p>
        <form action="" method="POST">
            {% csrf_token %} 
            <table>
                <tr>
                    <td>{{ form.new_password1.errors }}
                        <label for="id_new_password1"> Новый пароль:</label></td>
                    <td>{{ form.new_password1 }}</td>
                </tr>
                <tr>
                    <td>{{ form.new_password2.errors }}
                        <label for="id_new_password2"> Введите пароль еще раз:</label></td>
                    <td>{{ form.new_password2 }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="Изменить пароль" /></td>
                </tr>
            </table>
        </form>
    {% else %}
        <h1>Сброс не удался</h1>
        <p>Ссылка или повреждена или недействительна.Повторите попытку</p>
    {% endif %}

{% endblock %}

main/templates/main/profile.html
{% extends 'base/base.html' %}
{% load thumbnail %}
{% load bootstrap4 %}
{% load static %}


{% block title %}
    Профиль
{% endblock title %}

{% block content %}
    <h2>Профиль пользователя {{ user.username }}</h2>
    {% if user.first_name and user.last_name %} 
    <p>Доброго времени суток, {{ user.first_name }} {{ user.last_name }}!</p>
    {% else %} 
    <p>Доброго времени суток!</p>
    {% endif %} 
    <p><h4><a href="{% url 'main:profile_bb_add' %}">Добавить новость--></a></h4></p>
    <h3 class="mb-2">{{ rubric }}</h3>
    <div class="container-fluid mb-2">
    </div>
    {% if bbs %} 
        <ul class="list-unstyled">
            {% for bb in bbs %} 
            <li class="media my-5 p-3 border">
                {% url 'main:detail' rubric_pk=rubric.pk pk=bb.pk as url %} 
                <a href="{{ url }} {{ all }}">
                </a>
                <div class="media-body">
                    <h3><a href="{{ url }} {{ all }}">
                        {{ bb.title }}
                    </a></h3>
                    <div>{{ bb.content }}</div>
                    <p class="text-right forn-weight-bold">Источник {{ bb.source }}</p>
                    <p class="text-right font-italic">{{ bb.created_at }}</p>
                </div>
            </li>
            <p><h6><a href="{% url 'main:profile_bb_change' pk=bb.pk %}">Изменить новость--></a></h6></p>
            <p><h6><a href="{% url 'main:profile_bb_delete' pk=bb.pk %}">Удалить новость--></a></h6></p>
            <h3>Ваши новости</h3>
            {% endfor %}
        </ul>
    {% endif %}  
{% endblock content %}
    
    

main/templates/main/profile_bb_change.html
{% extends 'base/base.html' %}
{% load thumbnail %}
{% load bootstrap4 %}
{% load static %}

{% block title %}
    Изменение новостной записи - Профиль пользователя
{% endblock title %}

{% block content %}
    <h3>Изменение новости</h3>
    <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %} 
    {% bootstrap_form form layout='horizontal' %} 
    {% bootstrap_formset formset layout='horizontal' %} 
    {% buttons submit='Редактировать' %} {% endbuttons %} 
</form>
{% endblock content %}
    

main/templates/main/profile_bb_delete.html
{% extends 'base/base.html' %}
{% load thumbnail %}
{% load bootstrap4 %}
{% load static %}

{% block title %}
    Удаление новостной записи - Профиль пользователя
{% endblock title %}

{% block content %}
    <h3>Удаление новости</h3>
    <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %} 
    {% buttons submit='Удалить' %} {% endbuttons %} 
</form>
{% endblock content %}
    

main/templates/main/profile_detail.html
{% extends 'base/base.html' %} 
{% load bootstrap4 %} 
{% load static %}
{% load thumbnail %} 

{% block title %}
    {{ bb.title }} - {{ bb.rubric.name }}
{% endblock title %}

{% block content %}
    <div class="container-fluid mt-3">
        <!--<div class="row">-->
            <div class="col">
                <h3>{{ bb.title }}</h3>
                <p>{{ bb.content }}</p>
                <p class="font-weight-bold">Источник {{ bb.source }}</p>
                <!--<p>{{ bb.contacts }}</p>-->
                <p class="text-right forn-italic">Новость добавлена {{ bb.created_at }}</p>
            </div>
            {% if bb.image %} 
            <div class="col">
                <img src="{{ bb.image.url }}" alt="a" class="rounded float-right">
            {% endif %} 
            <!--<div class="col">
                <h3>{{ bb.title }}</h3>
                <p>{{ bb.content }}</p>
                <p class="font-weight-bold">{{ bb.source }}</p>
                <p>{{ bb.contacts }}</p>
                <p class="text-right forn-italic">Новость добавлена {{ bb.created_at }}</p>
            </div>-->
        </div>
    </div>
    {% if ais %} 
    <div class="d-flex justify-content-between flex-wrap mt-5">
        {% for ai in ais %} 
        <div>
            <img src="{{ ai.image.url }}" alt="b" class="additional-image">
        </div>
        {% endfor %} 
    </div>
    {% endif %} 
    <p>
        <a href="{% url 'main:by_rubric' pk=bb.rubric.pk %} {{ all }}">Назад</a>
    </p>
{% endblock content %}
    
    

main/templates/main/register_done.html
{% extends 'base/base.html' %} 
{% load bootstrap4 %} 

{% block title %}
    Регистрация завершена
{% endblock title %}

{% block content %}
   <h3>Регистрация пользователя завершена</h3>
    <p>На указанный вами адрес электронной почты отправлено сообщение</p>
    <p>Для активации пользователя, перейтите по ссылке в этом письме</p>
{% endblock content %}

main/templates/main/register_user.html
{% extends 'base/base.html' %} 
{% load bootstrap4 %} 

{% block title %}
    Регистрация
{% endblock title %}

{% block content %}
   <h3>Регистрация нового пользователя</h3>
        <form action="" method="POST">
            {% csrf_token %} 
            {% bootstrap_form form layout='horizontal' %} 
            {% buttons submit='Зарегистрироваться' %} {% endbuttons %} 
        </form>
{% endblock content %}
    
    

main/templates/main/reset.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}

{% block title %}
    Сброс пароля
{% endblock title %}

{% block content %}
    <h2>Сброс пароля пользователя {{ user.username }}</h2>
    <p>Пожалуйста введите свой адрес электронной почты</p>
    <p>Мы отправим вам писмьмо с сылкой для повторной активации</p>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-success" type="submit" value="Отправить инструкцию!">
        </form>
{% endblock content %}

main/templates/main/reset_done.html
{% extends 'base/base.html' %}
{% load bootstrap4 %} 
{% load  static %}

{% block title %}
    Сброс пароля
{% endblock title %}

{% block 
    content %}
    Мы успешно отправили вам письмо со ссылкой.
{% endblock 
    content %}
    
    