api/urls.py
from django.urls import path 
from .views import bbs #список новостей
from .views import BbDetailView#вывод отдельных сведений о выбранной новости
from .views import comments #вывод и добавление комментариев



urlpatterns = [
    path('bbs/<int:pk>/comments/', comments),
    path('bbs/<int:pk>/', BbDetailView.as_view()),
    path('bbs/', bbs),
]

astron/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('api/', include('api.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path 
from .views import index#главная
from .views import other_page#другие страницы
from .views import AstroLoginView#вход
from .views import profile#профиль
from .views import AstroLogoutView#выход
from .views import ChangeUserInfoView#изменение данных
from .views import AstroPasswordChangeView#смена пароля
from .views import RegisterUserView#регистрация
from .views import RegisterDoneView#сообщение о регистрации
from .views import user_activate#активация
from .views import DeleteUserView#удаление профиля 
#from .views import ResetPasswordView#сброс пароля
#from .views import ResetPasswordConfirmView#дтверждение сброса
#from .views import ResetPasswordCompleteView
#from .views import ResetPasswordDoneView
from .views import detail#детали новости
from .views import by_rubric#контроллер для рубрик
from django.conf.urls.static import static 
from astron import settings
from .views import profile_bb_detail#нконтроллер данных о новостях, загруженных пользователем
from .views import profile_bb_add#контроллер добавления новости
from .views import profile_bb_change#контроллер изменения новости
from .views import profile_bb_delete#контроллер удаления новости



app_name = 'main'

urlpatterns = [
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/logout/', AstroLogoutView.as_view(), name='logout'),
    path('accounts/password/change/', AstroPasswordChangeView.as_view(), name='password_change'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/change/<int:pk>/', profile_bb_change, name='profile_bb_change'),
    path('accounts/profile/delete/<int:pk>/', profile_bb_delete, name='profile_bb_delete'),
    path('accounts/profile/add/', profile_bb_add, name='profile_bb_add'),
    path('accounts/profile/<int:pk>/', profile_bb_detail, name='profile_bb_detail'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/login/', AstroLoginView.as_view(), name='login'),
   #path('accounts/password/reset/', ResetPasswordView.as_view(), name='reset'),
   #path('accounts/password/reset/confirm/', ResetPasswordConfirmView.as_view(), name='reset_confirm'),
   #path('accounts/password/reset/done/', ResetPasswordDoneView.as_view(), name='eset_done'),
   #path('accounts/password/reset/complete', ResetPasswordCompleteView.as_view(), name='reset_complete'),
    path('<int:rubric_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_rubric, name='by_rubric'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
]

main/forms.py
from django import forms 
from .models import AstroUser 
from django.contrib.auth import password_validation 
from django.core.exceptions import ValidationError
from .apps import user_registered
from .models import SuperRubric 
from .models import SubRubric 
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from .models import Bb 
from .models import AdditionalImage 
from captcha.fields import CaptchaField 
from .models import Comment 
#класс для ввода данных пользователя 
class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    class Meta:
        model = AstroUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')


#форма для занесения сведений о новом пользователe
class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password_one = forms.CharField(label='Пароль', 
        widget = forms.PasswordInput, 
        help_text = password_validation.password_validators_help_text_html())
    password_two = forms.CharField(label='Пароль(повторно)',
        widget = forms.PasswordInput,
        help_text = 'Введите тот же пароль еще раз для проверки')

    def clean_password_one(self):
        password_one = self.cleaned_data['password_one']
        if password_one:
            password_validation.validate_password(password_one)
        return password_one 

    def clean(self):
        super().clean()
        password_one = self.cleaned_data['password_one']
        password_two = self.cleaned_data['password_two']
        if password_one and password_two and password_one != password_two:
            errors = {'password_two': ValidationError(
                'Введенные вами пароли не совпадают', code = 'password_micmatch')
            }
            raise ValidationError(errors)
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password_one'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registered.send(RegisterUserForm, instance=user)
        return user 
    class Meta:
        model = AstroUser
        fields = ('username', 'email', 'password_one', 'password_two', 'first_name', 'last_name',
                'send_messages')


#создаем поле надрубрики
#@login_required
class SubRubricForm(forms.ModelForm):
    super_rubric = forms.ModelChoiceField(queryset=SuperRubric.objects.all(), 
                                            empty_label=None,
                                            label='Надрубрика',
                                            required=True)
    
    class Meta:
        model = SubRubric
        fields = '__all__'


#форма поиска на сайте
#@login_required
class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=20, label='')

#форма ввода новости
#форма ввода дополнительных иллюстраций
class BbForm(forms.ModelForm):
    class Meta:
        model = Bb 
        fields = '__all__' 
        widgets = {'author': forms.HiddenInput}

AIFormSet = inlineformset_factory(Bb, AdditionalImage, fields='__all__')


#форма комментариев для зарегистрированного пользователя
class UserCommentForm(forms.ModelForm):
    class Meta:
        model = Comment 
        exclude = ('is_active',)
        widgets = {'bb': forms.HiddenInput}

#форма для комментариев для гостей сайта
class GuestCommentForm(forms.ModelForm):
    captcha = CaptchaField(label='Введите текст с картинки', error_messages={'invalid': 'Неправильный текст'})
    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'bb': forms.HiddenInput}

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required 
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin#примесь для зарегистрированных пользователей
from django.views.generic.edit import UpdateView 
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy, reverse
from django.shortcuts import get_object_or_404
from .models import AstroUser
from .forms import ChangeUserInfoForm
from django.contrib.auth.views import PasswordChangeView 
from django.views.generic.edit import CreateView 
from .forms import RegisterUserForm
from django.views.generic.base import TemplateView  
from django.core.signing import BadSignature 
from .utilities import signer 
from django.views.generic.edit import DeleteView 
from django.contrib.auth import logout 
from django.contrib import messages 
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView
from django.core.paginator import Paginator 
from django.db.models import Q 
from .models import SubRubric, Bb
from .forms import SearchForm 
from django.shortcuts import redirect 
from .forms import BbForm
from .forms import AIFormSet
from .models import Comment 
from .forms import UserCommentForm 
from .forms import GuestCommentForm


#реализация контроллера главной страницы с помощью функции
def index(request):
    bbs = Bb.objects.filter(is_active=True)[:10]
    context = {'bbs': bbs}
    return render(request, 'main/index.html', context)

#генератор адресов
def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
        #поднятие исключения
    except TemplateDoesNotExist:
        #перехват исключения и вывод http404
        raise Http404
    return HttpResponse(template.render(request=request))

#контроллер страницы входа - расширение класа loginView
class AstroLoginView(LoginView):
    template_name = 'main/login.html'

#контролер профиля пользователя
@login_required#декоратор функции, подтверждающий, что пользователь вошел
def profile(request):
    bbs = Bb.objects.filter(author=request.user.pk)
    context = {'bbs': bbs}
    return render(request, 'main/profile.html', context)


#раелизация контроллера выхода через класс LogoutView
class AstroLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


#используем класс UpdateView для изменения пользовательских данных
class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AstroUser
    template_name = 'main/ch_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Данные пользователя успешно изменены'
    
    #получаем ключ текущего пользователя
    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk 
        return super().setup(request, *args, **kwargs)
    
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


#онтроллер изменения пароля создаем, расширяя класс PasswordChangeView
class AstroPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_ch.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль успешно изменен'

#контроллеро регистрации пользователя
class RegisterUserView(CreateView):
    model = AstroUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


#вывод сообщения о регистрации пользователя
class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


#контроллер активации
def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/bad.html')
    user = get_object_or_404(AstroUser, username=username)
    if user.is_activated:
        template = 'main/user_is_activated.html'
    else:
        template = 'main/activation_done.html'
        user.is_active = True 
        user.is_activated = True 
        user.save()
    return render(request, template)

#удаление профиля
class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AstroUser
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def post (self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Пользователь удален')
        return super().post(request, *args, **kwargs)
    
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


#
def by_rubric(request, pk):
    rubric = get_object_or_404(SubRubric, pk=pk)
    bbs = Bb.objects.filter(is_active=True, rubric=pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        bbs = bbs.filter(q)
    else:
        keyword = ''

    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(bbs, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1 
    page = paginator.get_page(page_num)
    context = {'rubric': rubric, 'page': page, 'bbs': page.object_list, 'form': form} 
    return render(request, 'main/by_rubric.html', context) 


#функция детального рассмотрения новости и комментариев
def detail(request, rubric_pk, pk):
    #bb = get_object_or_404(Bb, pk=pk)
    bb = Bb.objects.get(pk=pk)
    ais = bb.additionalimage_set.all()
    comments = Comment.objects.filter(bb=pk, is_active=True)
    initial = {'bb': bb.pk}
    if request.user.is_authenticated:
        initial['author'] = request.user.username
        form_class = UserCommentForm
    else:
        form_class = GuestCommentForm
    form = form_class(initial=initial)
    if request.method == 'POST':
        c_form = form_class(request.POST)
        if c_form.is_valid():
            c_form.save()
            messages.add_message(request, messages.SUCCESS, 'Комментарий успешно добавлен')
        else:
            form = c_form
            messages.add_message(request, messages.WARNING, 'Комментарий не добавлен')
    context = {'bb': bb, 'ais': ais, 'comments': comments, 'form': form}
    return render(request, 'main/detail.html', context)
    #context = {'bb': bb, 'ais': ais}
    #return render(request, 'main/profile_detail.html', context)

#контроллер для просмотра сведений о новостях добавленных одним пользователем
@login_required
def profile_bb_detail(request, rubric_pk, pk):
    bb = get_object_or_404(Bb, pk=pk)
    ais = bb.additionalimage_set.all()
    context = {'bb': bb, 'ais': ais}
    return render(request, 'main/detail.html', context)


#контроллер добавления новостей 
@login_required
def profile_bb_add(request):
    if request.method == 'POST':
        form = BbForm(request.POST, request.FILES)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Новость успешно добавлена') 
                return redirect('main:profile')
    else:
        form = BbForm(initial={'author': request.user.pk})
        formset = AIFormSet()
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_bb_add.html', context)
'''
при создании формы перед выводом страницы 
охранения мы заносим в поле author формы ключ текущего
пользователя, который станет автором объявления.
во время сохранения введенного объявления, при создании объектов
формы и набора форм, мы должны передать конструкторам их классов вторым по­
зиционным параметром словарь со всеми полученными файлами (он хранится
в атрибуте FILES объекта запроса). Если мы не сделаем этого, то отправленные
пользователем иллюстрации окажутся потерянными
при сохранении мы сначала выполняем валидацию и сохранение формы
самого объявления. Метод s ave ( ) в качестве результата возвращает сохраненную
запись, и эту запись мы должны передать через параметр instance конструктору
класса набора форм. Это нужно для того, чтобы все дополнительные иллюстрации
после сохранения оказались связанными с объявлением.
'''
#контроллер удаления и редактирования новости
@login_required
def profile_bb_change(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    if request.method == 'POST':
        form = BbForm(request.POST, request.FILES, instance=bb)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Новость отредактирована')
                return redirect('main:profile')
    else:
        form = BbForm(instance=bb)
        formset = AIFormSet(instance=bb)
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_bb_change.html', context)

@login_required
def profile_bb_delete(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    if request.method == 'POST':
        bb.delete()
        messages.add_message(request, messages.SUCCESS, 'Новость удалена')

main/templates/base/base.html
{% load thumbnail %} 
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>
    {% block title %}
        Главная страница
    {% endblock title %}
    Блог хакера
        </title> 
        {% bootstrap_css %}   
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    {% bootstrap_javascript jquery='slim' %} 
</head>
<body class="container-fluid">
    <header class="mb-4">
        <h2 class="text-right">Убежище Хакера</h2>
    </header>
    <div class="row">
        <ul class="nav nav-tabs">
            {% if user.is_authenticated %} 
                 <a href="#" class="nav-link dropdpwn-toggle"
                data-toggle="dropdown" role="button" 
                aria-haspopup="true" -expanded="false">Профиль</a>
                <div class="dropdown-menu">
                    <a href="{% url 'main:profile' %}" class="dropdown-item">Мои новости</a>
                    <a href="{% url 'main:profile_change' %}" class="dropdown-item">Изменить личные данные</a>
                    <a href="{% url 'main:password_change' %}" class="dropdown-item">Изменить пароль</a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'main:logout' %}" class="dropdown-item">Выйти</a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'main:profile_delete' %}" class="dropdown-item">Удалить</a>
            {% else %} 
            <li class="active">
                <a href="{% url 'main:login' %}" class="nav-link">Вход</a>
            </li>
            {% endif %} 
           </div>
           </li>
           </ul>
           </div>

           <ul class="nav nav-pills">
            <li class="active">
              <a href="{% url 'main:index' %}" class='red'>Главная</a>
            </li>
            <span><----------------></span>
            <li>
              <a href="{% url 'main:other' page='about' %}" class="light-green">Как пользоваться сайтом</a>
            </li>
            <span><-----------------></span>
            <li class="active">
                <a href="{% url 'main:register' %}" class="light-yellow">Регистрация</a>
                </li>
                <span><----------------></span>
              <li class="active">
            {% for rubric in rubrics %}  
                <a href="{% url 'main:by_rubric' pk=rubric.pk %}" class="nav-link">
                    {{ rubric.name }}
                    <h6><----подробнее----></h6>
                </a>
                </li>
            {% endfor %} 
    
           </ul>
    






          










            <!--<span class="nav-link root font-weight-bold">Солнечная система</span>
            <a href="#" class="nav-link">Меркурий</a>
            <a href="#" class="nav-link">Венера</a>
            <a href="#" class="nav-link">Земля</a>
            <a href="#" class="nav-link">Марс</a>
            <a href="#" class="nav-link">Юпитер</a>
            <a href="#" class="nav-link">Сатурн</a>
            <a href="#" class="nav-link">Уран</a>
            <a href="#" class="nav-link">Нептун</a>
            <a href="#" class="nav-link">Плутон и малые планеты</a>
            <a href="#" class="nav-link">Астероиды и кометы</a>


            <span class="nav-link root font-weight-bold">Галактика</span>
            <a href="#" class="nav-link">Млечный путь</a>
            <a href="#" class="nav-link">Шаровые скопления</a>
            <a href="#" class="nav-link">Рассеяные скопления</a>
            <a href="#" class="nav-link">Туманности</a>
            
            <span class="nav-link root font-weight-bold">Вселенная</span>
            <a href="#" class="nav-link">Галактики</a>
            <a href="#" class="nav-link">Квазары</a>
            <a href="#" class="nav-link">Сверхмассивные черные дыры</a>
            <a href="#" class="nav-link">Расширение Вселенной</a>
            
            <span class="nav-link root font-weight-bold">Звезды</span>
            <a href="#" class="nav-link">Солнце</a>
            <a href="#" class="nav-link">Сверхновые и новые звезды</a>
            <a href="#" class="nav-link">Черные и белые дыры</a>
            <a href="#" class="nav-link">Пульсары и магнетары</a>
            <a href="#" class="nav-link">Звезды карлики</a>
            <a href="#" class="nav-link">Экзопланеты и экзолуны</a>
            
            <span class="nav-link root font-weight-bold">Астротехника</span>
            <a href="#" class="nav-link">Телескопы и обсерватории</a>
            <a href="#" class="nav-link">Космические роботы</a>
           
            <span class="nav-link root font-weight-bold">Загадки Вселенной</span>
            <a href="#" class="nav-link">Загадки Солнечной системы</a>
            <a href="#" class="nav-link">Загадки других звезд и туманностей</a>
            <a href="#" class="nav-link">Загадки Млечного пути</a>
            <a href="#" class="nav-link">Загадки галактик и квазаров</a>
            <a href="#" class="nav-link">Загадки Вселенной</a>
            <a href="#" class="nav-link">Жизнь и разум</a>-->
        </nav>
        <section class="col border py-2">
            {% bootstrap_messages %}
            {% block content %}
             
            {% endblock content %}
                
        </section>
    </div>
    <footer class="mt-3">
        <p class="text-right font-italic">&copy; EHGWRabbit</p>
    </footer>
</body>
</html>